# fly.toml app configuration file generated for filemetadata-extract on 2023-10-27T17:35:26-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "filemetadata-extract"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
